---
- name: TIMESCALEDB | Add .pgpass file
  template:
    src: "{{ timescaledb_multinode_pgpass_template_file }}"
    dest: "{{ timescaledb_multinode_pgpass_path }}/.pgpass"
    owner: "{{ timescaledb_pg_user }}"
    group: "{{ timescaledb_pg_group }}"
    mode: 0600

- name: TIMESCALEDB | Add authentication configuration to postgresql.conf
  lineinfile:
    path: "/etc/postgresql/{{ timescaledb_pg_major }}/main/postgresql.conf"
    regexp: "#?timescaledb.passfile =.*"
    line: "timescaledb.passfile = '{{ timescaledb_multinode_pgpass_path }}/.pgpass'"
  notify:
    - timescaledb pg restart
