---

## Timescaledb Role

timescaledb_pg_major: 12
timescaledb_pg_user: "postgres"
timescaledb_pg_database: "timescaledb_db"

timescaledb_pg_database_owner: "timescaledb_testuser"
timescaledb_private_tmp: false

# Postgresql Role
pg_user: "postgres"
pg_major_release: "{{ timescaledb_pg_major }}"

pg_users:
  - name: "{{ timescaledb_pg_database_owner }}"
pg_databases:
  - name: "{{ timescaledb_pg_database }}"
    owner: "{{ timescaledb_pg_database_owner }}"