---

## Timescaledb Role
timescaledb_user: "timescaledb_testuser"

timescaledb_pg_major: 12
timescaledb_pg_user: "postgres"
timescaledb_pg_database: "timescaledb_db"

timescaledb_private_tmp: false

# Postgresql Role
pg_user: "postgres"
pg_major_release: "{{ timescaledb_pg_major }}"

pg_users:
  - name: "{{ timescaledb_user }}"
pg_databases:
  - name: "{{ timescaledb_pg_database }}"
    owner: "{{ timescaledb_user }}"